"""empty message

Revision ID: 135d6febb1b0
Revises: f17c3e55e89d
Create Date: 2018-01-22 09:45:33.203158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135d6febb1b0'
down_revision = 'f17c3e55e89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_creator'), 'contact', ['creator'], unique=False)
    op.create_table('publication_recipients',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'publication_id')
    )
    op.drop_table('pub_recipient_list')
    op.drop_table('publication_recipient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_recipient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_recipient_list',
    sa.Column('pub_recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('publication_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pub_recipient_id'], ['publication_recipient.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('pub_recipient_id', 'publication_id')
    )
    op.drop_table('publication_recipients')
    op.drop_index(op.f('ix_contact_creator'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
