"""empty message

Revision ID: 234822c673ff
Revises: 
Create Date: 2018-03-20 23:50:00.531580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234822c673ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Enum('viewer', 'writer', 'admin', 'superuser', name='user_roles'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('usergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('personal_group', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usergroup_label'), 'usergroup', ['label'], unique=True)
    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('db_type', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=256), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('database_name', sa.String(length=256), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_creator_user_id'), 'connection', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_connection_label'), 'connection', ['label'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_creator_user_id'), 'contact', ['creator_user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_published', sa.DateTime(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_creator_user_id'), 'report', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_report_label'), 'report', ['label'], unique=True)
    op.create_table('sql_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('raw_sql', sa.Text(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sql_query_creator_user_id'), 'sql_query', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_sql_query_label'), 'sql_query', ['label'], unique=True)
    op.create_table('user_perms',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'usergroup_id'),
    sa.UniqueConstraint('user_id', 'usergroup_id', name='UC_user_id_usergroup_id')
    )
    op.create_table('chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('sql_query_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sql_query_id'], ['sql_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_creator_user_id'), 'chart', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_chart_label'), 'chart', ['label'], unique=True)
    op.create_table('connection_perms',
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('connection_id', 'usergroup_id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Enum('manual', 'days_of_week', 'day_of_month', 'daily', 'hourly', 'every_ten_min', name='pub_frequency'), nullable=True),
    sa.Column('monday', sa.String(length=15), nullable=True),
    sa.Column('tuesday', sa.String(length=15), nullable=True),
    sa.Column('wednesday', sa.String(length=15), nullable=True),
    sa.Column('thursday', sa.String(length=15), nullable=True),
    sa.Column('friday', sa.String(length=15), nullable=True),
    sa.Column('saturday', sa.String(length=15), nullable=True),
    sa.Column('sunday', sa.String(length=15), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('pub_time', sa.Time(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('notification_or_attachment', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_creator_user_id'), 'publication', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_publication_report_id'), 'publication', ['report_id'], unique=False)
    op.create_table('query_perms',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['sql_query.id'], ),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'usergroup_id')
    )
    op.create_table('report_perms',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'usergroup_id')
    )
    op.create_table('chart_perms',
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('chart_id', 'usergroup_id')
    )
    op.create_table('publication_recipients',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'publication_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_recipients')
    op.drop_table('chart_perms')
    op.drop_table('report_perms')
    op.drop_table('query_perms')
    op.drop_index(op.f('ix_publication_report_id'), table_name='publication')
    op.drop_index(op.f('ix_publication_creator_user_id'), table_name='publication')
    op.drop_table('publication')
    op.drop_table('connection_perms')
    op.drop_index(op.f('ix_chart_label'), table_name='chart')
    op.drop_index(op.f('ix_chart_creator_user_id'), table_name='chart')
    op.drop_table('chart')
    op.drop_table('user_perms')
    op.drop_index(op.f('ix_sql_query_label'), table_name='sql_query')
    op.drop_index(op.f('ix_sql_query_creator_user_id'), table_name='sql_query')
    op.drop_table('sql_query')
    op.drop_index(op.f('ix_report_label'), table_name='report')
    op.drop_index(op.f('ix_report_creator_user_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_contact_creator_user_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_connection_label'), table_name='connection')
    op.drop_index(op.f('ix_connection_creator_user_id'), table_name='connection')
    op.drop_table('connection')
    op.drop_index(op.f('ix_usergroup_label'), table_name='usergroup')
    op.drop_table('usergroup')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
