"""empty message

Revision ID: a37a7e45b857
Revises: 2f3325e5b995
Create Date: 2018-03-20 23:47:20.342499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37a7e45b857'
down_revision = '2f3325e5b995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connection', 'label',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sql_query', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('usergroup', sa.Column('personal_group', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergroup', 'personal_group')
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sql_query', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connection', 'label',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('connection', 'creator_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
