"""empty message

Revision ID: c4580b315996
Revises: ef5f938ebed7
Create Date: 2018-01-26 00:15:35.202736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4580b315996'
down_revision = 'ef5f938ebed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_perms',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usergroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['usergroup_id'], ['usergroup.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'usergroup_id')
    )
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'usergroup_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usergroup_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user', 'usergroup', ['usergroup_id'], ['id'])
    op.drop_table('user_perms')
    # ### end Alembic commands ###
